{
 "title": "Prometheus-Test",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "System Application Uptime (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_application_uptime__seconds_{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Max Allowed Temp (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_cpu_max_allowed_temp___c_{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Max Recorded Temp (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_cpu_max_recorded_temp___c_{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_cpu_temperature___c_{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_cpu_usage____{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_disk_usage____{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max CPU Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_max_cpu_used____{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_max_memory_used__mb_{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_memory_usage__mb_{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min CPU Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_min_cpu_used____{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_min_memory_used__mb_{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Uptime (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "metricsmonitoringservice_system_os_uptime__seconds_{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Messages Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "mqttservice_messages_pending{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MQTT Connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "mqttservice_mqtt_connected{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TCP Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "tcpsocketservice_connected_clients{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Last Message Sent (seconds ago)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "tcpsocketservice_last_message_sent__seconds_ago_{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Message Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "tcpsocketservice_message_queue_size{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Server Healthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "tcpsocketservice_socket_server_healthy{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Total Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "tcpsocketservice_total_messages_sent{}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}