global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'reader'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.15.222:8443']
    basic_auth:
      username: "admin"
      password: "admin"
    tls_config:
      insecure_skip_verify: true
